#!/bin/sh

# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#

remote="$1"
url="$2"

status=0
sbt test "runMain go3d.Runner" || status=1

VERSION=$(grep 'version :=' build.sbt | cut -d '"' -f 2)
docker build --build-arg version=$VERSION -t test_image . || status=1

if [ $status -gt 0 ]; then
  commitmsg=$(git log --oneline | head -n 1 | cut -d' ' -f 2-)
  if echo $commitmsg | grep '^WIP:'; then
    echo >&2 "Found WIP commit, pushing in spite of failed test suite"
    status=0
  fi
fi

exit $status
