rules = [
  OrganizeImports
  RemoveUnused
  DisableSyntax
]

OrganizeImports.removeUnused = false

DisableSyntax.noVars = true
DisableSyntax.noThrows = false
DisableSyntax.noNulls = true
DisableSyntax.noReturns = false
DisableSyntax.noAsInstanceOf = true
DisableSyntax.noIsInstanceOf = true
