/*
 * SettingsDialog.java
 *
 * Created on August 30, 2003, 2:20 PM
 */

/**
 *
 * @author  i
 */
class SettingsDialog extends javax.swing.JDialog {

    int boardSize;
    
    int numHandicaps;
    
    int numPlayers;
    
    int color;

    protected J3DApp caller;

    /** Creates new form SettingsDialog */
    public SettingsDialog(java.awt.Frame parent, boolean modal, J3DApp caller) {
        super(parent, modal);
	this.caller = caller;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        boardSizeLabel1 = new javax.swing.JLabel();
        boardSizeSlider = new javax.swing.JSlider();
        colorLabel = new javax.swing.JLabel();
        colorComboBox = new javax.swing.JComboBox();
        startButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        
        getContentPane().setLayout(new java.awt.GridLayout(3, 0));
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        
        boardSizeLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boardSizeLabel1.setText("Board Size");
        boardSizeLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(boardSizeLabel1);
        
        boardSizeSlider.setFont(new java.awt.Font("Dialog", 0, 8));
        boardSizeSlider.setMajorTickSpacing(4);
        boardSizeSlider.setMaximum(25);
        boardSizeSlider.setMinimum(3);
        boardSizeSlider.setMinorTickSpacing(2);
        boardSizeSlider.setPaintLabels(true);
        boardSizeSlider.setPaintTicks(true);
        boardSizeSlider.setValue(7);
        boardSizeSlider.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boardSizeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                boardSizeSliderStateChanged(evt);
            }
        });
        
        getContentPane().add(boardSizeSlider);
        
        colorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        colorLabel.setText("Color");
        colorLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(colorLabel);
        
        colorComboBox.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        colorComboBox.setEnabled(false);
        colorComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                colorComboBoxItemStateChanged(evt);
            }
        });
        
        getContentPane().add(colorComboBox);
        
        startButton.setText("Start Game");
        startButton.setToolTipText("Click to start the game");
        startButton.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        
        getContentPane().add(startButton);
        
        cancelButton.setText("Cancel");
        cancelButton.setToolTipText("Click here to cancel the game and exit the program");
        cancelButton.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        
        getContentPane().add(cancelButton);
        
        pack();
    }//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        cancelGame ();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void colorComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_colorComboBoxItemStateChanged
        // Add your handling code here:
    }//GEN-LAST:event_colorComboBoxItemStateChanged

    private void boardSizeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_boardSizeSliderStateChanged
        boardSize = boardSizeSlider.getValue();
    }//GEN-LAST:event_boardSizeSliderStateChanged

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        startGame ();
    }//GEN-LAST:event_startButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    protected void startGame() {
    }
    
    protected void cancelGame () {
        System.exit (0);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new SettingsDialog(new javax.swing.JFrame(), true, null).setVisible (true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel boardSizeLabel1;
    private javax.swing.JSlider boardSizeSlider;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JComboBox colorComboBox;
    private javax.swing.JButton startButton;
    private javax.swing.JButton cancelButton;
    // End of variables declaration//GEN-END:variables

}
