/*
 * StartupDialog.java
 *
 * Created on August 30, 2003, 5:31 PM
 */

/**
 *
 * @author  i
 */
public class StartupDialog extends javax.swing.JDialog {

    protected String serverHost = "localhost";
    
    protected int serverPort = GoGrid.getServerPort ();

    protected J3DApp caller;
    
    /** Creates new form StartupDialog */
    public StartupDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        serverHostTextField.setText(serverHost);
        serverPortTextField.setText(""+serverPort);
    }

    /** Creates new form StartupDialog */
    public StartupDialog(java.awt.Frame parent, boolean modal, J3DApp caller) {
        super(parent, modal);
	this.caller = caller;
        initComponents();
        serverHostTextField.setText(serverHost);
        serverPortTextField.setText(""+serverPort);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        serverHostLabel = new javax.swing.JLabel();
        serverHostTextField = new javax.swing.JTextField();
        serverPortLabel = new javax.swing.JLabel();
        serverPortTextField = new javax.swing.JTextField();
        connectButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        
        getContentPane().setLayout(new java.awt.GridLayout(3, 0));
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        
        serverHostLabel.setText("Server hostname");
        getContentPane().add(serverHostLabel);
        
        serverHostTextField.setText("jTextField1");
        getContentPane().add(serverHostTextField);
        
        serverPortLabel.setText("Server port");
        getContentPane().add(serverPortLabel);
        
        serverPortTextField.setText("jTextField2");
        getContentPane().add(serverPortTextField);
        
        connectButton.setText("Connect");
        connectButton.setToolTipText("Connect to a server running on the given parameters");
        connectButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        connectButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });
        
        getContentPane().add(connectButton);
        
        cancelButton.setText("Cancel");
        cancelButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelButton.setName("Select a Server");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        
        getContentPane().add(cancelButton);
        
        pack();
    }//GEN-END:initComponents

    String getServerHost() {
        return serverHost;
    }    

    void setServerHost(String hostname) {
        serverHost = hostname;
    }
    
    int getServerPort() {
        return serverPort;
    }
    
    void setServerPort(int port) {
        serverPort = port;
    }
    
    protected void cancel () {
        System.exit (0);
    }
    
    protected void connect () {
	GoGrid.setServerPort (serverPort);
        if (caller != null) {
            caller.setHostname (serverHost);
        }
	this.closeDialog(null);
    }

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        cancel ();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_connectButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new StartupDialog(new javax.swing.JFrame(), true).show();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel serverHostLabel;
    private javax.swing.JTextField serverHostTextField;
    private javax.swing.JLabel serverPortLabel;
    private javax.swing.JTextField serverPortTextField;
    private javax.swing.JButton connectButton;
    private javax.swing.JButton cancelButton;
    // End of variables declaration//GEN-END:variables

}
