#!/usr/bin/env python3
"""Print the source files with the most uncovered statements from a scoverage XML report."""
import re
import sys
from collections import defaultdict

LIMIT = 25
# the report is generated by our own build; attributes are read with a regex rather than an XML
# parser, which keeps the script dependency-free
STATEMENT = re.compile(r"<statement\b([^>]*)>")
ATTRIBUTE = re.compile(r'([\w-]+)="([^"]*)"')


def uncovered_by_file(report):
    """Map each source file to [statement count, invoked statement count]."""
    counts = defaultdict(lambda: [0, 0])
    for match in STATEMENT.finditer(report):
        attributes = dict(ATTRIBUTE.findall(match.group(1)))
        if attributes.get("ignored") == "true":
            continue
        entry = counts[attributes.get("source", "?").split("/src/main/scala/")[-1]]
        entry[0] += 1
        entry[1] += attributes.get("invocation-count", "0") != "0"
    return counts


def main():
    with open(sys.argv[1], encoding="utf-8") as report_file:
        counts = uncovered_by_file(report_file.read())
    rows = sorted(counts.items(), key=lambda item: item[1][1] - item[1][0])
    print(f"{'uncovered':>9} {'total':>6} {'rate':>6}  file")
    for name, (total, invoked) in rows[:LIMIT]:
        print(f"{total - invoked:>9} {total:>6} {100 * invoked / total:>5.1f}%  {name}")


if __name__ == "__main__":
    main()
