#!/usr/bin/env python3
"""Print the source files with the most uncovered statements from the scoverage XML report."""
from collections import defaultdict
from pathlib import Path
import re

LIMIT = 25
REPORT_GLOB = "target/scala-*/scoverage-report/scoverage.xml"
# the report is generated by our own build; attributes are read with a regex rather than an XML
# parser, which keeps the script dependency-free
ATTRIBUTE = re.compile(r'([\w-]+)="([^"]*)"')


def uncovered_by_file(report):
    """Map each source file to [statement count, invoked statement count]."""
    counts = defaultdict(lambda: [0, 0])
    for chunk in report.split("<statement ")[1:]:
        attributes = dict(ATTRIBUTE.findall(chunk.split(">", 1)[0]))
        if attributes.get("ignored") == "true":
            continue
        entry = counts[attributes.get("source", "?").split("/src/main/scala/")[-1]]
        entry[0] += 1
        entry[1] += attributes.get("invocation-count", "0") != "0"
    return counts


def main():
    reports = sorted(Path(".").glob(REPORT_GLOB))
    if not reports:
        print(f"no coverage report matching {REPORT_GLOB}")
        return
    counts = uncovered_by_file(reports[-1].read_text(encoding="utf-8"))
    rows = sorted(counts.items(), key=lambda item: item[1][1] - item[1][0])
    print(f"{'uncovered':>9} {'total':>6} {'rate':>6}  file")
    for name, (total, invoked) in rows[:LIMIT]:
        print(f"{total - invoked:>9} {total:>6} {100 * invoked / total:>5.1f}%  {name}")


if __name__ == "__main__":
    main()
