#!/usr/bin/env python3
"""Print the source files with the most uncovered statements from the scoverage XML report."""
from collections import defaultdict
from pathlib import Path

LIMIT = 25
REPORT_GLOB = "target/scala-*/scoverage-report/scoverage.xml"


def attributes_of(tag_text):
    """Parse the name="value" attributes of one XML tag.

    The report is generated by our own build, so a plain string split is enough and keeps the
    script free of XML parser and regex dependencies.
    """
    parts = tag_text.split('"')
    return {name.strip().rstrip("="): value for name, value in zip(parts[0::2], parts[1::2])}


def uncovered_by_file(report):
    """Map each source file to [statement count, invoked statement count]."""
    counts = defaultdict(lambda: [0, 0])
    for chunk in report.split("<statement ")[1:]:
        # values may contain ">" (e.g. symbol="scala.Int.>") but never '"', so the tag ends at '">'
        attributes = attributes_of(chunk.split('">', 1)[0] + '"')
        if attributes.get("ignored") == "true":
            continue
        entry = counts[attributes.get("source", "?").split("/src/main/scala/")[-1]]
        entry[0] += 1
        entry[1] += attributes.get("invocation-count", "0") != "0"
    return counts


def main():
    """Print the files with the most uncovered statements from the newest report."""
    reports = sorted(Path(".").glob(REPORT_GLOB))
    if not reports:
        print(f"no coverage report matching {REPORT_GLOB}")
        return
    counts = uncovered_by_file(reports[-1].read_text(encoding="utf-8"))
    rows = sorted(counts.items(), key=lambda item: item[1][1] - item[1][0])
    print(f"{'uncovered':>9} {'total':>6} {'rate':>6}  file")
    for name, (total, invoked) in rows[:LIMIT]:
        print(f"{total - invoked:>9} {total:>6} {100 * invoked / total:>5.1f}%  {name}")


if __name__ == "__main__":
    main()
